import os
from collections.abc import Iterable
from pathlib import Path


def find_project_root_by_folder(start: Path, folder_names: Iterable[str]) -> Path | None:
    current = start.resolve()
    for parent in [current] + list(current.parents):
        for folder in folder_names:
            if (parent / folder).is_dir():
                return parent
    return None


class Paths:
    """Central place for all important paths."""

    # user project root (to be set dynamically from CLI)
    _user_root: Path | None = None

    # ------------------ SET/GET ------------------

    @classmethod
    def set_user_root(cls, path: Path) -> None:
        cls._user_root = path.resolve()

    @classmethod
    def user_root(cls) -> Path:
        if cls._user_root is not None:
            return cls._user_root

        env_root = os.getenv("PYTEST_GUI_ROOT")
        if env_root:
            return Path(env_root).resolve()

        raise RuntimeError("User project root is not set yet.")

    # ------------------ USER-DEPENDENT PATHS ------------------

    @classmethod
    def config(cls) -> Path:
        return cls.user_root() / "pytest_gui" / "default.yaml"

    @classmethod
    def log_dir(cls) -> Path:
        return cls.user_root() / "pytest_gui" / "logs"

    @classmethod
    def state_file(cls) -> Path:
        return cls.user_root() / "pytest_gui" / "widgets_state.json"

    @classmethod
    def log_file(cls) -> Path:
        return cls.log_dir() / "app.log"

    @classmethod
    def pytest_report(cls) -> Path:
        """Path to the JSON report generated by pytest-json-report plugin."""
        return cls.user_root() / "pytest_gui" / "results" / "pytest_report.json"
